#!/bin/bash

echo "--- Setting up node deb repos"
curl -sL https://deb.nodesource.com/setup_4.x | bash -

echo "--- Installing additional packages"
apt-get update 
apt-get -y install \
	vim \
	build-essential \
	sakura \
	nodejs \
	linux-headers-$(uname -r)

echo "--- Installing ESLint globally"
npm intsall eslint -g

echo "--- Installing VBox additions"
cp /media/cdrom/VBoxLinuxAdditions.run $HOME/
$HOME/VBoxLinuxAdditions.run
rm $HOME/VBoxLinuxAdditions.run

echo "========================================"
echo "FINAL TASKS"
echo "========================================"
echo
echo "- Sakura"
echo "  * Set Options > More > Set palette > Xterm"

